openapi: 3.0.0
servers:
  - url: https://prog3_td2
info:
  version: "latest"
  title: PROG3 - TD2
paths:
  /play_against:
    get:
      tags:
        - PlayAgainst
      summary: get all play_against
      operationId: getPlayAgainst
      responses:
        '200':
          description: List of play_against
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayAgain'
        '500':
          description: Internal server error
  /play_against/{id}:
    get:
      tags:
        - PlayAgainst
      summary: get play against by id
      operationId: getPlayAgainstById
      responses:
        '200':
          description: Play against by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayAgain'
        '500':
          description: Internal server error

  /teams:
    get:
      tags:
        - Teams
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /teams/{team_id}:
    get:
      tags:
        - Teams
      summary: get team by id
      operationId: getTeamById
      responses:
        200:
          description: Team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /teams/{team_id}/players:
    get:
      tags:
        - Teams
      summary: get players by team id
      operationId: getPlayersByTeamId
      responses:
        200:
          description: Players by team id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
  /teams/{team_id}/play_against:
    get:
      tags:
        - Teams
      summary: get play against by team id
      operationId: getPlayAgainstByTeam
      responses:
        200:
          description: Play against by team
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlayAgain'
        '500':
          description: Internal server error
  /teams/{team_id}/play_against/{play_against_id}:
    get:
      tags:
        - Teams
      summary: get play against by team id and play againstId
      operationId: getPlayAgainstByTeamIdAndPlayAgainstId
      responses:
        200:
          description: Play against by team id and play against id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayAgain'

  /goals:
    get:
      tags:
        - Goals
      summary: get all goals
      operationId: findAllGoals
      responses:
        '200':
          description: List of goals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Goal'
        '500':
          description: Internal server error
  /goals/{id}:
    get:
      tags:
        - Goals
      summary: get goal by id
      operationId: findGoalById
      responses:
        '200':
          description: Goal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goal'
        '500':
          description: Internal server error

  /players:
    get:
      tags:
        - Players
      summary: get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

  /sponsors:
    get:
      tags:
        - Sponsors
      summary: get all sponsors
      operationId: getAllSponsors
      responses:
        '200':
          description: List of sponsors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'
        '500':
          description: Internal server error
  /sponsors/{id}:
    get:
      tags:
        - Sponsors
      summary: get sponsor by id
      operationId: getSponsor
      responses:
        '200':
          description: only sponsor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sponsor'
        '500':
          description: Internal server error

components:
  schemas:
    CreatePlayAgain:
      type: object
      properties:
        team_1:
          $ref: '#/components/schemas/Team'
        team_2:
          $ref: '#/components/schemas/Team'
        datetime:
          type: string
          format: date-time
        stadium:
          type: string
    PlayAgain:
      type: object
      properties:
        id:
          type: integer
        team_1_score:
          type: integer
        team_2_score:
          type: integer
        goals:
          type: array
          items:
            $ref: '#/components/schemas/Goal'
        team_1:
          $ref: '#/components/schemas/Team'
        team_2:
          $ref: '#/components/schemas/Team'
        datetime:
          type: string
          format: date-time
    CreateTeam:
      type: object
      properties:
        name:
          type: string
    Team:
      type: object
      properties:
        id:
          type: integer
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        sponsors:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
      allOf:
        - $ref: '#/components/schemas/CreateTeam'
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        is_guardian:
          type: boolean
    CreatePlayer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        number:
          type: integer
        team_id:
          type: integer
    CreateSponsor:
      type: object
      properties:
        name:
          type: string
    Sponsor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Goal:
      type: object
      properties:
        id:
          type: integer
        play_against_id:
          type: integer
        player_id:
          type: integer
        time:
          type: integer
        is_on_goal:
          type: boolean